name: check potential conflicts
on: pull_request

jobs:
  build:
    name: potential-conflicts-checker
    runs-on: ubuntu-latest
    steps:
      - uses: outsideris/potential-conflicts-checker-action@0.1.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}

  # add github merge check
  pr-merge-check:
      name: PR Merge Bot
      runs-on: ubuntu-latest
      steps:
        - uses: squalrus/merge-bot@v0.4.5





